using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MabeyaECommerce.Domain;

public class City
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int provinceId { get; set; }
    public Province? Province { get; set; }

    public ICollection<Address> Addresses { get; set; } = new List<Address>();

}
public class CityConfiguration : IEntityTypeConfiguration<City>
{
    public void Configure(EntityTypeBuilder<City> builder)
    {
        builder
            .ToTable("Cities");
        builder.HasIndex(p => new { p.Name, p.provinceId })
            .IsUnique();

        builder
            .Property(p => p.Name)
            .IsRequired();

        builder
                .HasMany(p => p.Addresses)
                .WithOne(p => p.City!)
                .HasForeignKey(p => p.cityId)
                .OnDelete(DeleteBehavior.Restrict);
        builder.HasData(
           new City { Id = 1, provinceId = 1, Name = "ALADAĞ" },
new City { Id = 2, provinceId = 1, Name = "CEYHAN" },
new City { Id = 3, provinceId = 1, Name = "ÇUKUROVA" },
new City { Id = 4, provinceId = 1, Name = "FEKE" },
new City { Id = 5, provinceId = 1, Name = "İMAMOĞLU" },
new City { Id = 6, provinceId = 1, Name = "KARAİSALI" },
new City { Id = 7, provinceId = 1, Name = "KARATAŞ" },
new City { Id = 8, provinceId = 1, Name = "KOZAN" },
new City { Id = 9, provinceId = 1, Name = "POZANTI" },
new City { Id = 10, provinceId = 1, Name = "SAİMBEYLİ" },
new City { Id = 11, provinceId = 1, Name = "SARIÇAM" },
new City { Id = 12, provinceId = 1, Name = "SEYHAN" },
new City { Id = 13, provinceId = 1, Name = "TUFANBEYLİ" },
new City { Id = 14, provinceId = 1, Name = "YUMURTALIK" },
new City { Id = 15, provinceId = 1, Name = "YÜREĞİR" },
new City { Id = 16, provinceId = 2, Name = "ADIYAMAN MERKEZ" },
new City { Id = 17, provinceId = 2, Name = "BESNİ" },
new City { Id = 18, provinceId = 2, Name = "ÇELİKHAN" },
new City { Id = 19, provinceId = 2, Name = "GERGER" },
new City { Id = 20, provinceId = 2, Name = "GÖLBAŞI" },
new City { Id = 21, provinceId = 2, Name = "KAHTA" },
new City { Id = 22, provinceId = 2, Name = "SAMSAT" },
new City { Id = 23, provinceId = 2, Name = "SİNCİK" },
new City { Id = 24, provinceId = 2, Name = "TUT" },
new City { Id = 25, provinceId = 3, Name = "AFYON MERKEZ" },
new City { Id = 26, provinceId = 3, Name = "BAŞMAKÇI" },
new City { Id = 27, provinceId = 3, Name = "BAYAT" },
new City { Id = 28, provinceId = 3, Name = "BOLVADİN" },
new City { Id = 29, provinceId = 3, Name = "ÇAY" },
new City { Id = 30, provinceId = 3, Name = "ÇOBANLAR" },
new City { Id = 31, provinceId = 3, Name = "DAZKIRI" },
new City { Id = 32, provinceId = 3, Name = "DİNAR" },
new City { Id = 33, provinceId = 3, Name = "EMİRDAĞ" },
new City { Id = 34, provinceId = 3, Name = "EVCİLER" },
new City { Id = 35, provinceId = 3, Name = "HOCALAR" },
new City { Id = 36, provinceId = 3, Name = "İHSANİYE" },
new City { Id = 37, provinceId = 3, Name = "İSCEHİSAR" },
new City { Id = 38, provinceId = 3, Name = "KIZILÖREN" },
new City { Id = 39, provinceId = 3, Name = "SANDIKLI" },
new City { Id = 40, provinceId = 3, Name = "SİNCANLI" },
new City { Id = 41, provinceId = 3, Name = "SULTANDAĞI" },
new City { Id = 42, provinceId = 3, Name = "ŞUHUT" },
new City { Id = 43, provinceId = 4, Name = "AĞRI MERKEZ" },
new City { Id = 44, provinceId = 4, Name = "DİYADİN" },
new City { Id = 45, provinceId = 4, Name = "DOĞUBAYAZIT" },
new City { Id = 46, provinceId = 4, Name = "ELEŞKİRT" },
new City { Id = 47, provinceId = 4, Name = "HAMUR" },
new City { Id = 48, provinceId = 4, Name = "PATNOS" },
new City { Id = 49, provinceId = 4, Name = "TAŞLIÇAY" },
new City { Id = 50, provinceId = 4, Name = "TUTAK" },
new City { Id = 51, provinceId = 5, Name = "AMASYA MERKEZ" },
new City { Id = 52, provinceId = 5, Name = "GÖYNÜCEK" },
new City { Id = 53, provinceId = 5, Name = "GÜMÜŞHACIKÖY" },
new City { Id = 54, provinceId = 5, Name = "HAMAMÖZÜ" },
new City { Id = 55, provinceId = 5, Name = "MERZİFON" },
new City { Id = 56, provinceId = 5, Name = "SULUOVA" },
new City { Id = 57, provinceId = 5, Name = "TAŞOVA" },
new City { Id = 58, provinceId = 6, Name = "AKYURT" },
new City { Id = 59, provinceId = 6, Name = "ALTINDAĞ" },
new City { Id = 60, provinceId = 6, Name = "ANKARA" },
new City { Id = 61, provinceId = 6, Name = "AYAŞ" },
new City { Id = 62, provinceId = 6, Name = "BALÂ" },
new City { Id = 63, provinceId = 6, Name = "BEYPAZARI" },
new City { Id = 64, provinceId = 6, Name = "ÇAMLIDERE" },
new City { Id = 65, provinceId = 6, Name = "ÇANKAYA" },
new City { Id = 66, provinceId = 6, Name = "ÇUBUK" },
new City { Id = 67, provinceId = 6, Name = "ELMADAĞ" },
new City { Id = 68, provinceId = 6, Name = "ETİMESGUT" },
new City { Id = 69, provinceId = 6, Name = "EVREN" },
new City { Id = 70, provinceId = 6, Name = "GÖLBAŞI" },
new City { Id = 71, provinceId = 6, Name = "GÜDÜL" },
new City { Id = 72, provinceId = 6, Name = "HAYMANA" },
new City { Id = 73, provinceId = 6, Name = "KALECİK" },
new City { Id = 74, provinceId = 6, Name = "KAZAN" },
new City { Id = 75, provinceId = 6, Name = "KEÇİÖREN" },
new City { Id = 76, provinceId = 6, Name = "KIZILCAHAMAM" },
new City { Id = 77, provinceId = 6, Name = "MAMAK" },
new City { Id = 78, provinceId = 6, Name = "NALLIHAN" },
new City { Id = 79, provinceId = 6, Name = "POLATLI" },
new City { Id = 80, provinceId = 6, Name = "PURSAKLAR" },
new City { Id = 81, provinceId = 6, Name = "SİNCAN" },
new City { Id = 82, provinceId = 6, Name = "ŞEREFLİKOÇHİSAR" },
new City { Id = 83, provinceId = 6, Name = "YENİMAHALLE" },
new City { Id = 84, provinceId = 7, Name = "AKSEKİ" },
new City { Id = 85, provinceId = 7, Name = "AKSU/ANTALYA" },
new City { Id = 86, provinceId = 7, Name = "ALANYA" },
new City { Id = 87, provinceId = 7, Name = "ANTALYA MERKEZ" },
new City { Id = 88, provinceId = 7, Name = "DÖŞEMEALTI" },
new City { Id = 89, provinceId = 7, Name = "ELMALI" },
new City { Id = 90, provinceId = 7, Name = "FİNİKE" },
new City { Id = 91, provinceId = 7, Name = "GAZİPAŞA" },
new City { Id = 92, provinceId = 7, Name = "GÜNDOĞMUŞ" },
new City { Id = 93, provinceId = 7, Name = "İBRADI" },
new City { Id = 94, provinceId = 7, Name = "KALE" },
new City { Id = 95, provinceId = 7, Name = "KAŞ" },
new City { Id = 96, provinceId = 7, Name = "KEMER" },
new City { Id = 97, provinceId = 7, Name = "KEPEZ" },
new City { Id = 98, provinceId = 7, Name = "KONYAALTI" },
new City { Id = 99, provinceId = 7, Name = "KORKUTELİ" },
new City { Id = 100, provinceId = 7, Name = "KUMLUCA" },
new City { Id = 101, provinceId = 7, Name = "MANAVGAT" },
new City { Id = 102, provinceId = 7, Name = "MURATPAŞA" },
new City { Id = 103, provinceId = 7, Name = "SERİK" },
new City { Id = 104, provinceId = 8, Name = "ARDANUÇ" },
new City { Id = 105, provinceId = 8, Name = "ARHAVİ" },
new City { Id = 106, provinceId = 8, Name = "ARTVİN MERKEZ" },
new City { Id = 107, provinceId = 8, Name = "BORÇKA" },
new City { Id = 108, provinceId = 8, Name = "HOPA" },
new City { Id = 109, provinceId = 8, Name = "MURGUL" },
new City { Id = 110, provinceId = 8, Name = "ŞAVŞAT" },
new City { Id = 111, provinceId = 8, Name = "YUSUFELİ" },
new City { Id = 112, provinceId = 9, Name = "AYDIN MERKEZ" },
new City { Id = 113, provinceId = 9, Name = "BOZDOĞAN" },
new City { Id = 114, provinceId = 9, Name = "BUHARKENT" },
new City { Id = 115, provinceId = 9, Name = "ÇİNE" },
new City { Id = 116, provinceId = 9, Name = "DİDİM (YENİHİSAR)" },
new City { Id = 117, provinceId = 9, Name = "GERMENCİK" },
new City { Id = 118, provinceId = 9, Name = "İNCİRLİOVA" },
new City { Id = 119, provinceId = 9, Name = "KARACASU" },
new City { Id = 120, provinceId = 9, Name = "KARPUZLU" },
new City { Id = 121, provinceId = 9, Name = "KOÇARLI" },
new City { Id = 122, provinceId = 9, Name = "KÖŞK" },
new City { Id = 123, provinceId = 9, Name = "KUŞADASI" },
new City { Id = 124, provinceId = 9, Name = "KUYUCAK" },
new City { Id = 125, provinceId = 9, Name = "NAZİLLİ" },
new City { Id = 126, provinceId = 9, Name = "SÖKE" },
new City { Id = 127, provinceId = 9, Name = "SULTANHİSAR" },
new City { Id = 128, provinceId = 9, Name = "YENİPAZAR" },
new City { Id = 129, provinceId = 10, Name = "AYVALIK" },
new City { Id = 130, provinceId = 10, Name = "BALIKESİR MERKEZ" },
new City { Id = 131, provinceId = 10, Name = "BALYA" },
new City { Id = 132, provinceId = 10, Name = "BANDIRMA" },
new City { Id = 133, provinceId = 10, Name = "BİGADİÇ" },
new City { Id = 134, provinceId = 10, Name = "BURHANİYE" },
new City { Id = 135, provinceId = 10, Name = "DURSUNBEY" },
new City { Id = 136, provinceId = 10, Name = "EDREMİT" },
new City { Id = 137, provinceId = 10, Name = "ERDEK" },
new City { Id = 138, provinceId = 10, Name = "GÖMEÇ" },
new City { Id = 139, provinceId = 10, Name = "GÖNEN" },
new City { Id = 140, provinceId = 10, Name = "HAVRAN" },
new City { Id = 141, provinceId = 10, Name = "İVRİNDİ" },
new City { Id = 142, provinceId = 10, Name = "KEPSUT" },
new City { Id = 143, provinceId = 10, Name = "MANYAS" },
new City { Id = 144, provinceId = 10, Name = "MARMARA" },
new City { Id = 145, provinceId = 10, Name = "SAVAŞTEPE" },
new City { Id = 146, provinceId = 10, Name = "SINDIRGI" },
new City { Id = 147, provinceId = 10, Name = "SUSURLUK" },
new City { Id = 148, provinceId = 11, Name = "BİLECİK MERKEZ" },
new City { Id = 149, provinceId = 11, Name = "BOZÜYÜK" },
new City { Id = 150, provinceId = 11, Name = "GÖLPAZARI" },
new City { Id = 151, provinceId = 11, Name = "İNHİSAR" },
new City { Id = 152, provinceId = 11, Name = "OSMANELİ" },
new City { Id = 153, provinceId = 11, Name = "PAZARYERİ" },
new City { Id = 154, provinceId = 11, Name = "SÖĞÜT" },
new City { Id = 155, provinceId = 11, Name = "YENİPAZAR" },
new City { Id = 156, provinceId = 12, Name = "ADAKLI" },
new City { Id = 157, provinceId = 12, Name = "BİNGÖL MERKEZ" },
new City { Id = 158, provinceId = 12, Name = "GENÇ" },
new City { Id = 159, provinceId = 12, Name = "KARLIOVA" },
new City { Id = 160, provinceId = 12, Name = "KİĞI" },
new City { Id = 161, provinceId = 12, Name = "SOLHAN" },
new City { Id = 162, provinceId = 12, Name = "YAYLADERE" },
new City { Id = 163, provinceId = 12, Name = "YEDİSU" },
new City { Id = 164, provinceId = 13, Name = "ADİLCEVAZ" },
new City { Id = 165, provinceId = 13, Name = "AHLAT" },
new City { Id = 166, provinceId = 13, Name = "BİTLİS MERKEZ" },
new City { Id = 167, provinceId = 13, Name = "GÜROYMAK" },
new City { Id = 168, provinceId = 13, Name = "HİZAN" },
new City { Id = 169, provinceId = 13, Name = "MUTKİ" },
new City { Id = 170, provinceId = 13, Name = "TATVAN" },
new City { Id = 171, provinceId = 14, Name = "BOLU MERKEZ" },
new City { Id = 172, provinceId = 14, Name = "DÖRTDİVAN" },
new City { Id = 173, provinceId = 14, Name = "GEREDE" },
new City { Id = 174, provinceId = 14, Name = "GÖYNÜK" },
new City { Id = 175, provinceId = 14, Name = "KIBRISCIK" },
new City { Id = 176, provinceId = 14, Name = "MENGEN" },
new City { Id = 177, provinceId = 14, Name = "MUDURNU" },
new City { Id = 178, provinceId = 14, Name = "SEBEN" },
new City { Id = 179, provinceId = 14, Name = "YENİÇAĞA" },
new City { Id = 180, provinceId = 15, Name = "AĞLASUN" },
new City { Id = 181, provinceId = 15, Name = "ALTINYAYLA" },
new City { Id = 182, provinceId = 15, Name = "BUCAK" },
new City { Id = 183, provinceId = 15, Name = "BURDUR MERKEZ" },
new City { Id = 184, provinceId = 15, Name = "ÇAVDIR" },
new City { Id = 185, provinceId = 15, Name = "ÇELTİKÇİ" },
new City { Id = 186, provinceId = 15, Name = "GÖLHİSAR" },
new City { Id = 187, provinceId = 15, Name = "KARAMANLI" },
new City { Id = 188, provinceId = 15, Name = "KEMER" },
new City { Id = 189, provinceId = 15, Name = "TEFENNİ" },
new City { Id = 190, provinceId = 15, Name = "YEŞİLOVA" },
new City { Id = 191, provinceId = 16, Name = "BURSA MERKEZ" },
new City { Id = 192, provinceId = 16, Name = "BÜYÜKORHAN" },
new City { Id = 193, provinceId = 16, Name = "GEMLİK" },
new City { Id = 194, provinceId = 16, Name = "GÜRSU" },
new City { Id = 195, provinceId = 16, Name = "HARMANCIK" },
new City { Id = 196, provinceId = 16, Name = "İNEGÖL" },
new City { Id = 197, provinceId = 16, Name = "İZNİK" },
new City { Id = 198, provinceId = 16, Name = "KARACABEY" },
new City { Id = 199, provinceId = 16, Name = "KELES" },
new City { Id = 200, provinceId = 16, Name = "KESTEL" },
new City { Id = 201, provinceId = 16, Name = "MUDANYA" },
new City { Id = 202, provinceId = 16, Name = "MUSTAFA KEMAL PAŞA" },
new City { Id = 203, provinceId = 16, Name = "NİLÜFER" },
new City { Id = 204, provinceId = 16, Name = "ORHANELİ" },
new City { Id = 205, provinceId = 16, Name = "ORHANGAZİ" },
new City { Id = 206, provinceId = 16, Name = "OSMANGAZİ" },
new City { Id = 207, provinceId = 16, Name = "YENİŞEHİR" },
new City { Id = 208, provinceId = 16, Name = "YILDIRIM" },
new City { Id = 209, provinceId = 17, Name = "AYVACIK" },
new City { Id = 210, provinceId = 17, Name = "BAYRAMİÇ" },
new City { Id = 211, provinceId = 17, Name = "BİGA" },
new City { Id = 212, provinceId = 17, Name = "BOZCAADA" },
new City { Id = 213, provinceId = 17, Name = "ÇAN" },
new City { Id = 214, provinceId = 17, Name = "ÇANAKKALE MERKEZ" },
new City { Id = 215, provinceId = 17, Name = "ECEABAT" },
new City { Id = 216, provinceId = 17, Name = "EZİNE" },
new City { Id = 217, provinceId = 17, Name = "GELİBOLU" },
new City { Id = 218, provinceId = 17, Name = "GÖKÇEADA (İMROZ)" },
new City { Id = 219, provinceId = 17, Name = "LAPSEKİ" },
new City { Id = 220, provinceId = 17, Name = "YENİCE" },
new City { Id = 221, provinceId = 18, Name = "ATKARACALAR" },
new City { Id = 222, provinceId = 18, Name = "BAYRAMÖREN" },
new City { Id = 223, provinceId = 18, Name = "ÇANKIRI MERKEZ" },
new City { Id = 224, provinceId = 18, Name = "ÇERKEŞ" },
new City { Id = 225, provinceId = 18, Name = "ELDİVAN" },
new City { Id = 226, provinceId = 18, Name = "ILGAZ" },
new City { Id = 227, provinceId = 18, Name = "KIZILIRMAK" },
new City { Id = 228, provinceId = 18, Name = "KORGUN" },
new City { Id = 229, provinceId = 18, Name = "KURŞUNLU" },
new City { Id = 230, provinceId = 18, Name = "ORTA" },
new City { Id = 231, provinceId = 18, Name = "ŞABANÖZÜ" },
new City { Id = 232, provinceId = 18, Name = "YAPRAKLI" },
new City { Id = 233, provinceId = 19, Name = "ALACA" },
new City { Id = 234, provinceId = 19, Name = "BAYAT" },
new City { Id = 235, provinceId = 19, Name = "BOĞAZKALE" },
new City { Id = 236, provinceId = 19, Name = "ÇORUM MERKEZ" },
new City { Id = 237, provinceId = 19, Name = "DODURGA" },
new City { Id = 238, provinceId = 19, Name = "İSKİLİP" },
new City { Id = 239, provinceId = 19, Name = "KARGI" },
new City { Id = 240, provinceId = 19, Name = "LAÇİN" },
new City { Id = 241, provinceId = 19, Name = "MECİTÖZÜ" },
new City { Id = 242, provinceId = 19, Name = "OĞUZLAR" },
new City { Id = 243, provinceId = 19, Name = "ORTAKÖY" },
new City { Id = 244, provinceId = 19, Name = "OSMANCIK" },
new City { Id = 245, provinceId = 19, Name = "SUNGURLU" },
new City { Id = 246, provinceId = 19, Name = "UĞURLUDAĞ" },
new City { Id = 247, provinceId = 20, Name = "ACIPAYAM" },
new City { Id = 248, provinceId = 20, Name = "AKKÖY" },
new City { Id = 249, provinceId = 20, Name = "BABADAĞ" },
new City { Id = 250, provinceId = 20, Name = "BAKLAN" },
new City { Id = 251, provinceId = 20, Name = "BEKİLLİ" },
new City { Id = 252, provinceId = 20, Name = "BEYAĞAÇ" },
new City { Id = 253, provinceId = 20, Name = "BOZKURT" },
new City { Id = 254, provinceId = 20, Name = "BULDAN" },
new City { Id = 255, provinceId = 20, Name = "ÇAL" },
new City { Id = 256, provinceId = 20, Name = "ÇAMELİ" },
new City { Id = 257, provinceId = 20, Name = "ÇARDAK" },
new City { Id = 258, provinceId = 20, Name = "ÇİVRİL" },
new City { Id = 259, provinceId = 20, Name = "DENİZLİ MERKEZ" },
new City { Id = 260, provinceId = 20, Name = "GÜNEY" },
new City { Id = 261, provinceId = 20, Name = "HONAZ" },
new City { Id = 262, provinceId = 20, Name = "KALE" },
new City { Id = 263, provinceId = 20, Name = "SARAYKÖY" },
new City { Id = 264, provinceId = 20, Name = "SERİNHİSAR" },
new City { Id = 265, provinceId = 20, Name = "TAVAS" },
new City { Id = 266, provinceId = 21, Name = "BAĞLAR" },
new City { Id = 267, provinceId = 21, Name = "BİSMİL" },
new City { Id = 268, provinceId = 21, Name = "ÇERMİK" },
new City { Id = 269, provinceId = 21, Name = "ÇINAR" },
new City { Id = 270, provinceId = 21, Name = "ÇÜNGÜŞ" },
new City { Id = 271, provinceId = 21, Name = "DİCLE" },
new City { Id = 272, provinceId = 21, Name = "DİYARBAKIR MERKEZ" },
new City { Id = 273, provinceId = 21, Name = "EĞİL" },
new City { Id = 274, provinceId = 21, Name = "ERGANİ" },
new City { Id = 275, provinceId = 21, Name = "HANİ" },
new City { Id = 276, provinceId = 21, Name = "HAZRO" },
new City { Id = 277, provinceId = 21, Name = "KAYAPINAR" },
new City { Id = 278, provinceId = 21, Name = "KOCAKÖY" },
new City { Id = 279, provinceId = 21, Name = "KULP" },
new City { Id = 280, provinceId = 21, Name = "LİCE" },
new City { Id = 281, provinceId = 21, Name = "SİLVAN" },
new City { Id = 282, provinceId = 21, Name = "SUR" },
new City { Id = 283, provinceId = 21, Name = "YENİŞEHİR/DİYARBAKIR" },
new City { Id = 284, provinceId = 22, Name = "EDİRNE MERKEZ" },
new City { Id = 285, provinceId = 22, Name = "ENEZ" },
new City { Id = 286, provinceId = 22, Name = "HAVSA" },
new City { Id = 287, provinceId = 22, Name = "İPSALA" },
new City { Id = 288, provinceId = 22, Name = "KEŞAN" },
new City { Id = 289, provinceId = 22, Name = "LALAPAŞA" },
new City { Id = 290, provinceId = 22, Name = "MERİÇ" },
new City { Id = 291, provinceId = 22, Name = "SÜLOĞLU" },
new City { Id = 292, provinceId = 22, Name = "UZUNKÖPRÜ" },
new City { Id = 293, provinceId = 23, Name = "AĞIN" },
new City { Id = 294, provinceId = 23, Name = "ALACAKAYA" },
new City { Id = 295, provinceId = 23, Name = "ARICAK" },
new City { Id = 296, provinceId = 23, Name = "BASKİL" },
new City { Id = 297, provinceId = 23, Name = "ELAZIĞ MERKEZ" },
new City { Id = 298, provinceId = 23, Name = "KARAKOÇAN" },
new City { Id = 299, provinceId = 23, Name = "KEBAN" },
new City { Id = 300, provinceId = 23, Name = "KOVANCILAR" },
new City { Id = 301, provinceId = 23, Name = "MADEN" },
new City { Id = 302, provinceId = 23, Name = "PALU" },
new City { Id = 303, provinceId = 23, Name = "SİVRİCE" },
new City { Id = 304, provinceId = 24, Name = "ÇAYIRLI" },
new City { Id = 305, provinceId = 24, Name = "ERZİNCAN MERKEZ" },
new City { Id = 306, provinceId = 24, Name = "İLİÇ" },
new City { Id = 307, provinceId = 24, Name = "KEMAH" },
new City { Id = 308, provinceId = 24, Name = "KEMALİYE" },
new City { Id = 309, provinceId = 24, Name = "OTLUKBELİ" },
new City { Id = 310, provinceId = 24, Name = "REFAHİYE" },
new City { Id = 311, provinceId = 24, Name = "TERCAN" },
new City { Id = 312, provinceId = 24, Name = "ÜZÜMLÜ" },
new City { Id = 313, provinceId = 25, Name = "AŞKALE" },
new City { Id = 314, provinceId = 25, Name = "ÇAT" },
new City { Id = 315, provinceId = 25, Name = "ERZURUM MERKEZ" },
new City { Id = 316, provinceId = 25, Name = "HINIS" },
new City { Id = 317, provinceId = 25, Name = "HORASAN" },
new City { Id = 318, provinceId = 25, Name = "ILICA" },
new City { Id = 319, provinceId = 25, Name = "İSPİR" },
new City { Id = 320, provinceId = 25, Name = "KARAÇOBAN" },
new City { Id = 321, provinceId = 25, Name = "KARAYAZI" },
new City { Id = 322, provinceId = 25, Name = "KÖPRÜKÖY" },
new City { Id = 323, provinceId = 25, Name = "NARMAN" },
new City { Id = 324, provinceId = 25, Name = "OLTU" },
new City { Id = 325, provinceId = 25, Name = "OLUR" },
new City { Id = 326, provinceId = 25, Name = "PALANDÖKEN" },
new City { Id = 327, provinceId = 25, Name = "PASİNLER" },
new City { Id = 328, provinceId = 25, Name = "PAZARYOLU" },
new City { Id = 329, provinceId = 25, Name = "ŞENKAYA" },
new City { Id = 330, provinceId = 25, Name = "TEKMAN" },
new City { Id = 331, provinceId = 25, Name = "TORTUM" },
new City { Id = 332, provinceId = 25, Name = "UZUNDERE" },
new City { Id = 333, provinceId = 25, Name = "YAKUTİYE" },
new City { Id = 334, provinceId = 26, Name = "ALPU" },
new City { Id = 335, provinceId = 26, Name = "BEYLİKOVA" },
new City { Id = 336, provinceId = 26, Name = "ÇİFTELER" },
new City { Id = 337, provinceId = 26, Name = "ESKİŞEHİR MERKEZ" },
new City { Id = 338, provinceId = 26, Name = "GÜNYÜZÜ" },
new City { Id = 339, provinceId = 26, Name = "HAN" },
new City { Id = 340, provinceId = 26, Name = "İNÖNÜ" },
new City { Id = 341, provinceId = 26, Name = "MAHMUDİYE" },
new City { Id = 342, provinceId = 26, Name = "MİHALGAZİ" },
new City { Id = 343, provinceId = 26, Name = "MİHALIÇÇIK" },
new City { Id = 344, provinceId = 26, Name = "ODUNPAZARI" },
new City { Id = 345, provinceId = 26, Name = "SARICAKAYA" },
new City { Id = 346, provinceId = 26, Name = "SEYİTGAZİ" },
new City { Id = 347, provinceId = 26, Name = "SİVRİHİSAR" },
new City { Id = 348, provinceId = 26, Name = "TEPEBAŞI" },
new City { Id = 349, provinceId = 27, Name = "ARABAN" },
new City { Id = 350, provinceId = 27, Name = "GAZİANTEP MERKEZ" },
new City { Id = 351, provinceId = 27, Name = "İSLAHİYE" },
new City { Id = 352, provinceId = 27, Name = "KARKAMIŞ" },
new City { Id = 353, provinceId = 27, Name = "NİZİP" },
new City { Id = 354, provinceId = 27, Name = "NURDAĞI" },
new City { Id = 355, provinceId = 27, Name = "OĞUZELİ" },
new City { Id = 356, provinceId = 27, Name = "ŞAHİNBEY" },
new City { Id = 357, provinceId = 27, Name = "ŞEHİTKAMİL" },
new City { Id = 358, provinceId = 27, Name = "YAVUZELİ" },
new City { Id = 359, provinceId = 28, Name = "ALUCRA" },
new City { Id = 360, provinceId = 28, Name = "BULANCAK" },
new City { Id = 361, provinceId = 28, Name = "ÇAMOLUK" },
new City { Id = 362, provinceId = 28, Name = "ÇANAKÇI" },
new City { Id = 363, provinceId = 28, Name = "DERELİ" },
new City { Id = 364, provinceId = 28, Name = "DOĞANKENT" },
new City { Id = 365, provinceId = 28, Name = "ESPİYE" },
new City { Id = 366, provinceId = 28, Name = "EYNESİL" },
new City { Id = 367, provinceId = 28, Name = "GİRESUN MERKEZ" },
new City { Id = 368, provinceId = 28, Name = "GÖRELE" },
new City { Id = 369, provinceId = 28, Name = "GÜCE" },
new City { Id = 370, provinceId = 28, Name = "KEŞAP" },
new City { Id = 371, provinceId = 28, Name = "PİRAZİZ" },
new City { Id = 372, provinceId = 28, Name = "ŞEBİNKARAHİSAR" },
new City { Id = 373, provinceId = 28, Name = "TİREBOLU" },
new City { Id = 374, provinceId = 28, Name = "YAĞLIDERE" },
new City { Id = 375, provinceId = 29, Name = "GÜMÜŞHANE MERKEZ" },
new City { Id = 376, provinceId = 29, Name = "KELKİT" },
new City { Id = 377, provinceId = 29, Name = "KÖSE" },
new City { Id = 378, provinceId = 29, Name = "KÜRTÜN" },
new City { Id = 379, provinceId = 29, Name = "ŞİRAN" },
new City { Id = 380, provinceId = 29, Name = "TORUL" },
new City { Id = 381, provinceId = 30, Name = "ÇUKURCA" },
new City { Id = 382, provinceId = 30, Name = "HAKKARİ MERKEZ" },
new City { Id = 383, provinceId = 30, Name = "ŞEMDİNLİ" },
new City { Id = 384, provinceId = 30, Name = "YÜKSEKOVA" },
new City { Id = 385, provinceId = 31, Name = "ALTINÖZÜ" },
new City { Id = 386, provinceId = 31, Name = "BELEN" },
new City { Id = 387, provinceId = 31, Name = "DÖRTYOL" },
new City { Id = 388, provinceId = 31, Name = "ERZİN" },
new City { Id = 389, provinceId = 31, Name = "HASSA" },
new City { Id = 390, provinceId = 31, Name = "HATAY MERKEZ" },
new City { Id = 391, provinceId = 31, Name = "İSKENDERUN" },
new City { Id = 392, provinceId = 31, Name = "KIRIKHAN" },
new City { Id = 393, provinceId = 31, Name = "KUMLU" },
new City { Id = 394, provinceId = 31, Name = "REYHANLI" },
new City { Id = 395, provinceId = 31, Name = "SAMANDAĞ" },
new City { Id = 396, provinceId = 31, Name = "YAYLADAĞI" },
new City { Id = 397, provinceId = 32, Name = "AKSU" },
new City { Id = 398, provinceId = 32, Name = "ATABEY" },
new City { Id = 399, provinceId = 32, Name = "EĞİRDİR" },
new City { Id = 400, provinceId = 32, Name = "GELENDOST" },
new City { Id = 401, provinceId = 32, Name = "GÖNEN" },
new City { Id = 402, provinceId = 32, Name = "ISPARTA MERKEZ" },
new City { Id = 403, provinceId = 32, Name = "KEÇİBORLU" },
new City { Id = 404, provinceId = 32, Name = "SENİRKENT" },
new City { Id = 405, provinceId = 32, Name = "SÜTÇÜLER" },
new City { Id = 406, provinceId = 32, Name = "ŞARKİKARAAĞAÇ" },
new City { Id = 407, provinceId = 32, Name = "ULUBORLU" },
new City { Id = 408, provinceId = 32, Name = "YALVAÇ" },
new City { Id = 409, provinceId = 32, Name = "YENİŞARBADEMLİ" },
new City { Id = 410, provinceId = 33, Name = "AKDENİZ" },
new City { Id = 411, provinceId = 33, Name = "ANAMUR" },
new City { Id = 412, provinceId = 33, Name = "AYDINCIK" },
new City { Id = 413, provinceId = 33, Name = "BOZYAZI" },
new City { Id = 414, provinceId = 33, Name = "ÇAMLIYAYLA" },
new City { Id = 415, provinceId = 33, Name = "ERDEMLİ" },
new City { Id = 416, provinceId = 33, Name = "GÜLNAR" },
new City { Id = 417, provinceId = 33, Name = "İÇEL MERKEZ" },
new City { Id = 418, provinceId = 33, Name = "MEZİTLİ" },
new City { Id = 419, provinceId = 33, Name = "MUT" },
new City { Id = 420, provinceId = 33, Name = "SİLİFKE" },
new City { Id = 421, provinceId = 33, Name = "TARSUS" },
new City { Id = 422, provinceId = 33, Name = "TOROSLAR" },
new City { Id = 423, provinceId = 33, Name = "YENİŞEHİR/MERSİN" },
new City { Id = 424, provinceId = 34, Name = "ADALAR" },
new City { Id = 425, provinceId = 34, Name = "ARNAVUTKÖY" },
new City { Id = 426, provinceId = 34, Name = "ATAŞEHİR" },
new City { Id = 427, provinceId = 34, Name = "AVCILAR" },
new City { Id = 428, provinceId = 34, Name = "BAĞCILAR" },
new City { Id = 429, provinceId = 34, Name = "BAHÇELİEVLER" },
new City { Id = 430, provinceId = 34, Name = "BAKIRKÖY" },
new City { Id = 431, provinceId = 34, Name = "BAŞAKŞEHİR" },
new City { Id = 432, provinceId = 34, Name = "BAYRAMPAŞA" },
new City { Id = 433, provinceId = 34, Name = "BEŞİKTAŞ" },
new City { Id = 434, provinceId = 34, Name = "BEYKOZ" },
new City { Id = 435, provinceId = 34, Name = "BEYLİKDÜZÜ" },
new City { Id = 436, provinceId = 34, Name = "BEYOĞLU" },
new City { Id = 437, provinceId = 34, Name = "BÜYÜKÇEKMECE" },
new City { Id = 438, provinceId = 34, Name = "ÇATALCA" },
new City { Id = 439, provinceId = 34, Name = "ÇEKMEKÖY" },
new City { Id = 440, provinceId = 34, Name = "EMİNÖNÜ" },
new City { Id = 441, provinceId = 34, Name = "ESENLER" },
new City { Id = 442, provinceId = 34, Name = "ESENYURT" },
new City { Id = 443, provinceId = 34, Name = "EYÜP" },
new City { Id = 444, provinceId = 34, Name = "FATİH" },
new City { Id = 445, provinceId = 34, Name = "GAZİOSMANPAŞA" },
new City { Id = 446, provinceId = 34, Name = "GÜNGÖREN" },
new City { Id = 447, provinceId = 34, Name = "İSTANBUL MERKEZ" },
new City { Id = 448, provinceId = 34, Name = "KADIKÖY" },
new City { Id = 449, provinceId = 34, Name = "KAĞITHANE" },
new City { Id = 450, provinceId = 34, Name = "KARTAL" },
new City { Id = 451, provinceId = 34, Name = "KÜÇÜKÇEKMECE" },
new City { Id = 452, provinceId = 34, Name = "MALTEPE" },
new City { Id = 453, provinceId = 34, Name = "PENDİK" },
new City { Id = 454, provinceId = 34, Name = "SANCAKTEPE" },
new City { Id = 455, provinceId = 34, Name = "SARIYER" },
new City { Id = 456, provinceId = 34, Name = "SİLİVRİ" },
new City { Id = 457, provinceId = 34, Name = "SULTANBEYLİ" },
new City { Id = 458, provinceId = 34, Name = "SULTANGAZİ" },
new City { Id = 459, provinceId = 34, Name = "ŞİLE" },
new City { Id = 460, provinceId = 34, Name = "ŞİŞLİ" },
new City { Id = 461, provinceId = 34, Name = "TUZLA" },
new City { Id = 462, provinceId = 34, Name = "ÜMRANİYE" },
new City { Id = 463, provinceId = 34, Name = "ÜSKÜDAR" },
new City { Id = 464, provinceId = 34, Name = "ZEYTİNBURNU" },
new City { Id = 465, provinceId = 35, Name = "ALİAĞA" },
new City { Id = 466, provinceId = 35, Name = "BALÇOVA" },
new City { Id = 467, provinceId = 35, Name = "BAYINDIR" },
new City { Id = 468, provinceId = 35, Name = "BAYRAKLI" },
new City { Id = 469, provinceId = 35, Name = "BERGAMA" },
new City { Id = 470, provinceId = 35, Name = "BEYDAĞ" },
new City { Id = 471, provinceId = 35, Name = "BORNOVA" },
new City { Id = 472, provinceId = 35, Name = "BUCA" },
new City { Id = 473, provinceId = 35, Name = "ÇEŞME" },
new City { Id = 474, provinceId = 35, Name = "ÇİĞLİ" },
new City { Id = 475, provinceId = 35, Name = "DİKİLİ" },
new City { Id = 476, provinceId = 35, Name = "FOÇA" },
new City { Id = 477, provinceId = 35, Name = "GAZİEMİR" },
new City { Id = 478, provinceId = 35, Name = "GÜZELBAHÇE" },
new City { Id = 479, provinceId = 35, Name = "İZMİR MERKEZ" },
new City { Id = 480, provinceId = 35, Name = "KARABAĞLAR" },
new City { Id = 481, provinceId = 35, Name = "KARABURUN" },
new City { Id = 482, provinceId = 35, Name = "KARŞIYAKA" },
new City { Id = 483, provinceId = 35, Name = "KEMALPAŞA" },
new City { Id = 484, provinceId = 35, Name = "KINIK" },
new City { Id = 485, provinceId = 35, Name = "KİRAZ" },
new City { Id = 486, provinceId = 35, Name = "KONAK" },
new City { Id = 487, provinceId = 35, Name = "MENDERES" },
new City { Id = 488, provinceId = 35, Name = "MENEMEN" },
new City { Id = 489, provinceId = 35, Name = "NARLIDERE" },
new City { Id = 490, provinceId = 35, Name = "ÖDEMİŞ" },
new City { Id = 491, provinceId = 35, Name = "SEFERİHİSAR" },
new City { Id = 492, provinceId = 35, Name = "SELÇUK" },
new City { Id = 493, provinceId = 35, Name = "TİRE" },
new City { Id = 494, provinceId = 35, Name = "TORBALI" },
new City { Id = 495, provinceId = 35, Name = "URLA" },
new City { Id = 496, provinceId = 36, Name = "AKYAKA" },
new City { Id = 497, provinceId = 36, Name = "ARPAÇAY" },
new City { Id = 498, provinceId = 36, Name = "DİGOR" },
new City { Id = 499, provinceId = 36, Name = "KAĞIZMAN" },
new City { Id = 500, provinceId = 36, Name = "KARS MERKEZ" },
new City { Id = 501, provinceId = 36, Name = "SARIKAMIŞ" },
new City { Id = 502, provinceId = 36, Name = "SELİM" },
new City { Id = 503, provinceId = 36, Name = "SUSUZ" },
new City { Id = 504, provinceId = 37, Name = "ABANA" },
new City { Id = 505, provinceId = 37, Name = "AĞLI" },
new City { Id = 506, provinceId = 37, Name = "ARAÇ" },
new City { Id = 507, provinceId = 37, Name = "AZDAVAY" },
new City { Id = 508, provinceId = 37, Name = "BOZKURT" },
new City { Id = 509, provinceId = 37, Name = "CİDE" },
new City { Id = 510, provinceId = 37, Name = "ÇATALZEYTİN" },
new City { Id = 511, provinceId = 37, Name = "DADAY" },
new City { Id = 512, provinceId = 37, Name = "DEVREKÂNİ" },
new City { Id = 513, provinceId = 37, Name = "DOĞANYURT" },
new City { Id = 514, provinceId = 37, Name = "HANÖNÜ" },
new City { Id = 515, provinceId = 37, Name = "İHSANGAZİ" },
new City { Id = 516, provinceId = 37, Name = "İNEBOLU" },
new City { Id = 517, provinceId = 37, Name = "KASTAMONU MERKEZ" },
new City { Id = 518, provinceId = 37, Name = "KÜRE" },
new City { Id = 519, provinceId = 37, Name = "PINARBAŞI" },
new City { Id = 520, provinceId = 37, Name = "SEYDİLER" },
new City { Id = 521, provinceId = 37, Name = "ŞENPAZAR" },
new City { Id = 522, provinceId = 37, Name = "TAŞKÖPRÜ" },
new City { Id = 523, provinceId = 37, Name = "TOSYA" },
new City { Id = 524, provinceId = 38, Name = "AKKIŞLA" },
new City { Id = 525, provinceId = 38, Name = "BÜNYAN" },
new City { Id = 526, provinceId = 38, Name = "DEVELİ" },
new City { Id = 527, provinceId = 38, Name = "FELAHİYE" },
new City { Id = 528, provinceId = 38, Name = "HACILAR" },
new City { Id = 529, provinceId = 38, Name = "İNCESU" },
new City { Id = 530, provinceId = 38, Name = "KAYSERİ MERKEZ" },
new City { Id = 531, provinceId = 38, Name = "KOCASİNAN" },
new City { Id = 532, provinceId = 38, Name = "MELİKGAZİ" },
new City { Id = 533, provinceId = 38, Name = "ÖZVATAN" },
new City { Id = 534, provinceId = 38, Name = "PINARBAŞI" },
new City { Id = 535, provinceId = 38, Name = "SARIOĞLAN" },
new City { Id = 536, provinceId = 38, Name = "SARIZ" },
new City { Id = 537, provinceId = 38, Name = "TALAS" },
new City { Id = 538, provinceId = 38, Name = "TOMARZA" },
new City { Id = 539, provinceId = 38, Name = "YAHYALI" },
new City { Id = 540, provinceId = 38, Name = "YEŞİLHİSAR" },
new City { Id = 541, provinceId = 39, Name = "BABAESKİ" },
new City { Id = 542, provinceId = 39, Name = "DEMİRKÖY" },
new City { Id = 543, provinceId = 39, Name = "KIRKLARELİ MERKEZ" },
new City { Id = 544, provinceId = 39, Name = "KOFÇAZ" },
new City { Id = 545, provinceId = 39, Name = "LÜLEBURGAZ" },
new City { Id = 546, provinceId = 39, Name = "PEHLİVANKÖY" },
new City { Id = 547, provinceId = 39, Name = "PINARHİSAR" },
new City { Id = 548, provinceId = 39, Name = "VİZE" },
new City { Id = 549, provinceId = 40, Name = "AKÇAKENT" },
new City { Id = 550, provinceId = 40, Name = "AKPINAR" },
new City { Id = 551, provinceId = 40, Name = "BOZTEPE" },
new City { Id = 552, provinceId = 40, Name = "ÇİÇEKDAĞI" },
new City { Id = 553, provinceId = 40, Name = "KAMAN" },
new City { Id = 554, provinceId = 40, Name = "KIRŞEHİR MERKEZ" },
new City { Id = 555, provinceId = 40, Name = "MUCUR" },
new City { Id = 556, provinceId = 41, Name = "BAŞİSKELE" },
new City { Id = 557, provinceId = 41, Name = "ÇAYIROVA" },
new City { Id = 558, provinceId = 41, Name = "DARICA" },
new City { Id = 559, provinceId = 41, Name = "DERİNCE" },
new City { Id = 560, provinceId = 41, Name = "DİLOVASI" },
new City { Id = 561, provinceId = 41, Name = "GEBZE" },
new City { Id = 562, provinceId = 41, Name = "GÖLCÜK" },
new City { Id = 563, provinceId = 41, Name = "İZMİT" },
new City { Id = 564, provinceId = 41, Name = "KANDIRA" },
new City { Id = 565, provinceId = 41, Name = "KARAMÜRSEL" },
new City { Id = 566, provinceId = 41, Name = "KARTEPE" },
new City { Id = 567, provinceId = 41, Name = "KOCAELİ MERKEZ (İZMİT)" },
new City { Id = 568, provinceId = 41, Name = "KÖRFEZ" },
new City { Id = 569, provinceId = 42, Name = "AHIRLI" },
new City { Id = 570, provinceId = 42, Name = "AKÖREN" },
new City { Id = 571, provinceId = 42, Name = "AKŞEHİR" },
new City { Id = 572, provinceId = 42, Name = "ALTINEKİN" },
new City { Id = 573, provinceId = 42, Name = "BEYŞEHİR" },
new City { Id = 574, provinceId = 42, Name = "BOZKIR" },
new City { Id = 575, provinceId = 42, Name = "CİHANBEYLİ" },
new City { Id = 576, provinceId = 42, Name = "ÇELTİK" },
new City { Id = 577, provinceId = 42, Name = "ÇUMRA" },
new City { Id = 578, provinceId = 42, Name = "DERBENT" },
new City { Id = 579, provinceId = 42, Name = "DEREBUCAK" },
new City { Id = 580, provinceId = 42, Name = "DOĞANHİSAR" },
new City { Id = 581, provinceId = 42, Name = "EMİRGAZİ" },
new City { Id = 582, provinceId = 42, Name = "EREĞLİ" },
new City { Id = 583, provinceId = 42, Name = "GÜNEYSINIR" },
new City { Id = 584, provinceId = 42, Name = "HADIM" },
new City { Id = 585, provinceId = 42, Name = "HALKAPINAR" },
new City { Id = 586, provinceId = 42, Name = "HÜYÜK" },
new City { Id = 587, provinceId = 42, Name = "ILGIN" },
new City { Id = 588, provinceId = 42, Name = "KADINHANI" },
new City { Id = 589, provinceId = 42, Name = "KARAPINAR" },
new City { Id = 590, provinceId = 42, Name = "KARATAY" },
new City { Id = 591, provinceId = 42, Name = "KONYA MERKEZ" },
new City { Id = 592, provinceId = 42, Name = "KULU" },
new City { Id = 593, provinceId = 42, Name = "MERAM" },
new City { Id = 594, provinceId = 42, Name = "SARAYÖNÜ" },
new City { Id = 595, provinceId = 42, Name = "SELÇUKLU" },
new City { Id = 596, provinceId = 42, Name = "SEYDİŞEHİR" },
new City { Id = 597, provinceId = 42, Name = "TAŞKENT" },
new City { Id = 598, provinceId = 42, Name = "TUZLUKÇU" },
new City { Id = 599, provinceId = 42, Name = "YALIHÜYÜK" },
new City { Id = 600, provinceId = 42, Name = "YUNAK" },
new City { Id = 601, provinceId = 43, Name = "ALTINTAŞ" },
new City { Id = 602, provinceId = 43, Name = "ASLANAPA" },
new City { Id = 603, provinceId = 43, Name = "ÇAVDARHİSAR" },
new City { Id = 604, provinceId = 43, Name = "DOMANİÇ" },
new City { Id = 605, provinceId = 43, Name = "DUMLUPINAR" },
new City { Id = 606, provinceId = 43, Name = "EMET" },
new City { Id = 607, provinceId = 43, Name = "GEDİZ" },
new City { Id = 608, provinceId = 43, Name = "HİSARCIK" },
new City { Id = 609, provinceId = 43, Name = "KÜTAHYA MERKEZ" },
new City { Id = 610, provinceId = 43, Name = "PAZARLAR" },
new City { Id = 611, provinceId = 43, Name = "SİMAV" },
new City { Id = 612, provinceId = 43, Name = "ŞAPHANE" },
new City { Id = 613, provinceId = 43, Name = "TAVŞANLI" },
new City { Id = 614, provinceId = 44, Name = "AKÇADAĞ" },
new City { Id = 615, provinceId = 44, Name = "ARAPGİR" },
new City { Id = 616, provinceId = 44, Name = "ARGUVAN" },
new City { Id = 617, provinceId = 44, Name = "BATTALGAZİ" },
new City { Id = 618, provinceId = 44, Name = "DARENDE" },
new City { Id = 619, provinceId = 44, Name = "DOĞANŞEHİR" },
new City { Id = 620, provinceId = 44, Name = "DOĞANYOL" },
new City { Id = 621, provinceId = 44, Name = "HEKİMHAN" },
new City { Id = 622, provinceId = 44, Name = "KALE" },
new City { Id = 623, provinceId = 44, Name = "KULUNCAK" },
new City { Id = 624, provinceId = 44, Name = "MALATYA MERKEZ" },
new City { Id = 625, provinceId = 44, Name = "PÜTÜRGE" },
new City { Id = 626, provinceId = 44, Name = "YAZIHAN" },
new City { Id = 627, provinceId = 44, Name = "YEŞİLYURT" },
new City { Id = 628, provinceId = 45, Name = "AHMETLİ" },
new City { Id = 629, provinceId = 45, Name = "AKHİSAR" },
new City { Id = 630, provinceId = 45, Name = "ALAŞEHİR" },
new City { Id = 631, provinceId = 45, Name = "DEMİRCİ" },
new City { Id = 632, provinceId = 45, Name = "GÖLMARMARA" },
new City { Id = 633, provinceId = 45, Name = "GÖRDES" },
new City { Id = 634, provinceId = 45, Name = "KIRKAĞAÇ" },
new City { Id = 635, provinceId = 45, Name = "KÖPRÜBAŞI" },
new City { Id = 636, provinceId = 45, Name = "KULA" },
new City { Id = 637, provinceId = 45, Name = "MANİSA MERKEZ" },
new City { Id = 638, provinceId = 45, Name = "SALİHLİ" },
new City { Id = 639, provinceId = 45, Name = "SARIGÖL" },
new City { Id = 640, provinceId = 45, Name = "SARUHANLI" },
new City { Id = 641, provinceId = 45, Name = "SELENDİ" },
new City { Id = 642, provinceId = 45, Name = "SOMA" },
new City { Id = 643, provinceId = 45, Name = "TURGUTLU" },
new City { Id = 644, provinceId = 46, Name = "AFŞİN" },
new City { Id = 645, provinceId = 46, Name = "ANDIRIN" },
new City { Id = 646, provinceId = 46, Name = "ÇAĞLIYANCERİT" },
new City { Id = 647, provinceId = 46, Name = "EKİNÖZÜ" },
new City { Id = 648, provinceId = 46, Name = "ELBİSTAN" },
new City { Id = 649, provinceId = 46, Name = "GÖKSUN" },
new City { Id = 650, provinceId = 46, Name = "KAHRAMANMARAŞ MERKEZ" },
new City { Id = 651, provinceId = 46, Name = "NURHAK" },
new City { Id = 652, provinceId = 46, Name = "PAZARCIK" },
new City { Id = 653, provinceId = 46, Name = "TÜRKOĞLU" },
new City { Id = 654, provinceId = 47, Name = "DARGEÇİT" },
new City { Id = 655, provinceId = 47, Name = "DERİK" },
new City { Id = 656, provinceId = 47, Name = "KIZILTEPE" },
new City { Id = 657, provinceId = 47, Name = "MARDİN MERKEZ" },
new City { Id = 658, provinceId = 47, Name = "MAZIDAĞI" },
new City { Id = 659, provinceId = 47, Name = "MİDYAT" },
new City { Id = 660, provinceId = 47, Name = "NUSAYBİN" },
new City { Id = 661, provinceId = 47, Name = "ÖMERLİ" },
new City { Id = 662, provinceId = 47, Name = "SAVUR" },
new City { Id = 663, provinceId = 47, Name = "YEŞİLLİ" },
new City { Id = 664, provinceId = 48, Name = "BODRUM" },
new City { Id = 665, provinceId = 48, Name = "DALAMAN" },
new City { Id = 666, provinceId = 48, Name = "DATÇA" },
new City { Id = 667, provinceId = 48, Name = "FETHİYE" },
new City { Id = 668, provinceId = 48, Name = "KAVAKLIDERE" },
new City { Id = 669, provinceId = 48, Name = "KÖYCEĞİZ" },
new City { Id = 670, provinceId = 48, Name = "MARMARİS" },
new City { Id = 671, provinceId = 48, Name = "MİLAS" },
new City { Id = 672, provinceId = 48, Name = "MUĞLA MERKEZ" },
new City { Id = 673, provinceId = 48, Name = "ORTACA" },
new City { Id = 674, provinceId = 48, Name = "ULA" },
new City { Id = 675, provinceId = 48, Name = "YATAĞAN" },
new City { Id = 676, provinceId = 49, Name = "BULANIK" },
new City { Id = 677, provinceId = 49, Name = "HASKÖY" },
new City { Id = 678, provinceId = 49, Name = "KORKUT" },
new City { Id = 679, provinceId = 49, Name = "MALAZGİRT" },
new City { Id = 680, provinceId = 49, Name = "MUŞ MERKEZ" },
new City { Id = 681, provinceId = 49, Name = "VARTO" },
new City { Id = 682, provinceId = 50, Name = "ACIGÖL" },
new City { Id = 683, provinceId = 50, Name = "AVANOS" },
new City { Id = 684, provinceId = 50, Name = "DERİNKUYU" },
new City { Id = 685, provinceId = 50, Name = "GÜLŞEHİR" },
new City { Id = 686, provinceId = 50, Name = "HACIBEKTAŞ" },
new City { Id = 687, provinceId = 50, Name = "KOZAKLI" },
new City { Id = 688, provinceId = 50, Name = "NEVŞEHİR MERKEZ" },
new City { Id = 689, provinceId = 50, Name = "ÜRGÜP" },
new City { Id = 690, provinceId = 51, Name = "ALTUNHİSAR" },
new City { Id = 691, provinceId = 51, Name = "BOR" },
new City { Id = 692, provinceId = 51, Name = "ÇAMARDI" },
new City { Id = 693, provinceId = 51, Name = "ÇİFTLİK" },
new City { Id = 694, provinceId = 51, Name = "NİĞDE MERKEZ" },
new City { Id = 695, provinceId = 51, Name = "ULUKIŞLA" },
new City { Id = 696, provinceId = 52, Name = "AKKUŞ" },
new City { Id = 697, provinceId = 52, Name = "AYBASTI" },
new City { Id = 698, provinceId = 52, Name = "ÇAMAŞ" },
new City { Id = 699, provinceId = 52, Name = "ÇATALPINAR" },
new City { Id = 700, provinceId = 52, Name = "ÇAYBAŞI" },
new City { Id = 701, provinceId = 52, Name = "FATSA" },
new City { Id = 702, provinceId = 52, Name = "GÖLKÖY" },
new City { Id = 703, provinceId = 52, Name = "GÜLYALI" },
new City { Id = 704, provinceId = 52, Name = "GÜRGENTEPE" },
new City { Id = 705, provinceId = 52, Name = "İKİZCE" },
new City { Id = 706, provinceId = 52, Name = "KABADÜZ" },
new City { Id = 707, provinceId = 52, Name = "KABATAŞ" },
new City { Id = 708, provinceId = 52, Name = "KORGAN" },
new City { Id = 709, provinceId = 52, Name = "KUMRU" },
new City { Id = 710, provinceId = 52, Name = "MESUDİYE" },
new City { Id = 711, provinceId = 52, Name = "ORDU MERKEZ" },
new City { Id = 712, provinceId = 52, Name = "PERŞEMBE" },
new City { Id = 713, provinceId = 52, Name = "ULUBEY" },
new City { Id = 714, provinceId = 52, Name = "ÜNYE" },
new City { Id = 715, provinceId = 53, Name = "ARDEŞEN" },
new City { Id = 716, provinceId = 53, Name = "ÇAMLIHEMŞİN" },
new City { Id = 717, provinceId = 53, Name = "ÇAYELİ" },
new City { Id = 718, provinceId = 53, Name = "DEREPAZARI" },
new City { Id = 719, provinceId = 53, Name = "FINDIKLI" },
new City { Id = 720, provinceId = 53, Name = "GÜNEYSU" },
new City { Id = 721, provinceId = 53, Name = "HEMŞİN" },
new City { Id = 722, provinceId = 53, Name = "İKİZDERE" },
new City { Id = 723, provinceId = 53, Name = "İYİDERE" },
new City { Id = 724, provinceId = 53, Name = "KALKANDERE" },
new City { Id = 725, provinceId = 53, Name = "PAZAR" },
new City { Id = 726, provinceId = 53, Name = "RİZE MERKEZ" },
new City { Id = 727, provinceId = 54, Name = "ADAPAZARI" },
new City { Id = 728, provinceId = 54, Name = "AKYAZI" },
new City { Id = 729, provinceId = 54, Name = "ARİFİYE" },
new City { Id = 730, provinceId = 54, Name = "ERENLER" },
new City { Id = 731, provinceId = 54, Name = "FERİZLİ" },
new City { Id = 732, provinceId = 54, Name = "GEYVE" },
new City { Id = 733, provinceId = 54, Name = "HENDEK" },
new City { Id = 734, provinceId = 54, Name = "KARAPÜRÇEK" },
new City { Id = 735, provinceId = 54, Name = "KARASU" },
new City { Id = 736, provinceId = 54, Name = "KAYNARCA" },
new City { Id = 737, provinceId = 54, Name = "KOCAALİ" },
new City { Id = 738, provinceId = 54, Name = "PAMUKOVA" },
new City { Id = 739, provinceId = 54, Name = "SAKARYA MERKEZ (ADAPAZARI)" },
new City { Id = 740, provinceId = 54, Name = "SAPANCA" },
new City { Id = 741, provinceId = 54, Name = "SERDİVAN" },
new City { Id = 742, provinceId = 54, Name = "SÖĞÜTLÜ" },
new City { Id = 743, provinceId = 54, Name = "TARAKLI" },
new City { Id = 744, provinceId = 55, Name = "ALAÇAM" },
new City { Id = 745, provinceId = 55, Name = "ASARCIK" },
new City { Id = 746, provinceId = 55, Name = "ATAKUM" },
new City { Id = 747, provinceId = 55, Name = "AYVACIK" },
new City { Id = 748, provinceId = 55, Name = "BAFRA" },
new City { Id = 749, provinceId = 55, Name = "CANİK" },
new City { Id = 750, provinceId = 55, Name = "ÇARŞAMBA" },
new City { Id = 751, provinceId = 55, Name = "HAVZA" },
new City { Id = 752, provinceId = 55, Name = "İLKADIM" },
new City { Id = 753, provinceId = 55, Name = "KAVAK" },
new City { Id = 754, provinceId = 55, Name = "LADİK" },
new City { Id = 755, provinceId = 55, Name = "ONDOKUZMAYIS" },
new City { Id = 756, provinceId = 55, Name = "SALIPAZARI" },
new City { Id = 757, provinceId = 55, Name = "SAMSUN MERKEZ" },
new City { Id = 758, provinceId = 55, Name = "TEKKEKÖY" },
new City { Id = 759, provinceId = 55, Name = "TERME" },
new City { Id = 760, provinceId = 55, Name = "VEZİRKÖPRÜ" },
new City { Id = 761, provinceId = 55, Name = "YAKAKENT" },
new City { Id = 762, provinceId = 56, Name = "AYDINLAR" },
new City { Id = 763, provinceId = 56, Name = "BAYKAN" },
new City { Id = 764, provinceId = 56, Name = "ERUH" },
new City { Id = 765, provinceId = 56, Name = "KURTALAN" },
new City { Id = 766, provinceId = 56, Name = "PERVARİ" },
new City { Id = 767, provinceId = 56, Name = "SİİRT MERKEZ" },
new City { Id = 768, provinceId = 56, Name = "ŞİRVAN" },
new City { Id = 769, provinceId = 57, Name = "AYANCIK" },
new City { Id = 770, provinceId = 57, Name = "BOYABAT" },
new City { Id = 771, provinceId = 57, Name = "DİKMEN" },
new City { Id = 772, provinceId = 57, Name = "DURAĞAN" },
new City { Id = 773, provinceId = 57, Name = "ERFELEK" },
new City { Id = 774, provinceId = 57, Name = "GERZE" },
new City { Id = 775, provinceId = 57, Name = "SARAYDÜZÜ" },
new City { Id = 776, provinceId = 57, Name = "SİNOP MERKEZ" },
new City { Id = 777, provinceId = 57, Name = "TÜRKELİ" },
new City { Id = 778, provinceId = 58, Name = "AKINCILAR" },
new City { Id = 779, provinceId = 58, Name = "ALTINYAYLA" },
new City { Id = 780, provinceId = 58, Name = "DİVRİĞİ" },
new City { Id = 781, provinceId = 58, Name = "DOĞANŞAR" },
new City { Id = 782, provinceId = 58, Name = "GEMEREK" },
new City { Id = 783, provinceId = 58, Name = "GÖLOVA" },
new City { Id = 784, provinceId = 58, Name = "GÜRÜN" },
new City { Id = 785, provinceId = 58, Name = "HAFİK" },
new City { Id = 786, provinceId = 58, Name = "İMRANLI" },
new City { Id = 787, provinceId = 58, Name = "KANGAL" },
new City { Id = 788, provinceId = 58, Name = "KOYULHİSAR" },
new City { Id = 789, provinceId = 58, Name = "SİVAS MERKEZ" },
new City { Id = 790, provinceId = 58, Name = "SUŞEHRİ" },
new City { Id = 791, provinceId = 58, Name = "ŞARKIŞLA" },
new City { Id = 792, provinceId = 58, Name = "ULAŞ" },
new City { Id = 793, provinceId = 58, Name = "YILDIZELİ" },
new City { Id = 794, provinceId = 58, Name = "ZARA" },
new City { Id = 795, provinceId = 59, Name = "ÇERKEZKÖY" },
new City { Id = 796, provinceId = 59, Name = "ÇORLU" },
new City { Id = 797, provinceId = 59, Name = "HAYRABOLU" },
new City { Id = 798, provinceId = 59, Name = "MALKARA" },
new City { Id = 799, provinceId = 59, Name = "MARMARAEREĞLİSİ" },
new City { Id = 800, provinceId = 59, Name = "MURATLI" },
new City { Id = 801, provinceId = 59, Name = "SARAY" },
new City { Id = 802, provinceId = 59, Name = "ŞARKÖY" },
new City { Id = 803, provinceId = 59, Name = "TEKİRDAĞ MERKEZ" },
new City { Id = 804, provinceId = 60, Name = "ALMUS" },
new City { Id = 805, provinceId = 60, Name = "ARTOVA" },
new City { Id = 806, provinceId = 60, Name = "BAŞÇİFTLİK" },
new City { Id = 807, provinceId = 60, Name = "ERBAA" },
new City { Id = 808, provinceId = 60, Name = "NİKSAR" },
new City { Id = 809, provinceId = 60, Name = "PAZAR" },
new City { Id = 810, provinceId = 60, Name = "REŞADİYE" },
new City { Id = 811, provinceId = 60, Name = "SULUSARAY" },
new City { Id = 812, provinceId = 60, Name = "TOKAT MERKEZ" },
new City { Id = 813, provinceId = 60, Name = "TURHAL" },
new City { Id = 814, provinceId = 60, Name = "YEŞİLYURT" },
new City { Id = 815, provinceId = 60, Name = "ZİLE" },
new City { Id = 816, provinceId = 61, Name = "AKÇAABAT" },
new City { Id = 817, provinceId = 61, Name = "ARAKLI" },
new City { Id = 818, provinceId = 61, Name = "ARSİN" },
new City { Id = 819, provinceId = 61, Name = "BEŞİKDÜZÜ" },
new City { Id = 820, provinceId = 61, Name = "ÇARŞIBAŞI" },
new City { Id = 821, provinceId = 61, Name = "ÇAYKARA" },
new City { Id = 822, provinceId = 61, Name = "DERNEKPAZARI" },
new City { Id = 823, provinceId = 61, Name = "DÜZKÖY" },
new City { Id = 824, provinceId = 61, Name = "HAYRAT" },
new City { Id = 825, provinceId = 61, Name = "KÖPRÜBAŞI" },
new City { Id = 826, provinceId = 61, Name = "MAÇKA" },
new City { Id = 827, provinceId = 61, Name = "OF" },
new City { Id = 828, provinceId = 61, Name = "SÜRMENE" },
new City { Id = 829, provinceId = 61, Name = "ŞALPAZARI" },
new City { Id = 830, provinceId = 61, Name = "TONYA" },
new City { Id = 831, provinceId = 61, Name = "TRABZON MERKEZ" },
new City { Id = 832, provinceId = 61, Name = "VAKFIKEBİR" },
new City { Id = 833, provinceId = 61, Name = "YOMRA" },
new City { Id = 834, provinceId = 62, Name = "ÇEMİŞGEZEK" },
new City { Id = 835, provinceId = 62, Name = "HOZAT" },
new City { Id = 836, provinceId = 62, Name = "MAZGİRT" },
new City { Id = 837, provinceId = 62, Name = "NAZIMİYE" },
new City { Id = 838, provinceId = 62, Name = "OVACIK" },
new City { Id = 839, provinceId = 62, Name = "PERTEK" },
new City { Id = 840, provinceId = 62, Name = "PÜLÜMÜR" },
new City { Id = 841, provinceId = 62, Name = "TUNCELİ MERKEZ" },
new City { Id = 842, provinceId = 63, Name = "AKÇAKALE" },
new City { Id = 843, provinceId = 63, Name = "BİRECİK" },
new City { Id = 844, provinceId = 63, Name = "BOZOVA" },
new City { Id = 845, provinceId = 63, Name = "CEYLANPINAR" },
new City { Id = 846, provinceId = 63, Name = "HALFETİ" },
new City { Id = 847, provinceId = 63, Name = "HARRAN" },
new City { Id = 848, provinceId = 63, Name = "HİLVAN" },
new City { Id = 849, provinceId = 63, Name = "SİVEREK" },
new City { Id = 850, provinceId = 63, Name = "SURUÇ" },
new City { Id = 851, provinceId = 63, Name = "ŞANLIURFA MERKEZ" },
new City { Id = 852, provinceId = 63, Name = "VİRANŞEHİR" },
new City { Id = 853, provinceId = 64, Name = "BANAZ" },
new City { Id = 854, provinceId = 64, Name = "EŞME" },
new City { Id = 855, provinceId = 64, Name = "KARAHALLI" },
new City { Id = 856, provinceId = 64, Name = "SİVASLI" },
new City { Id = 857, provinceId = 64, Name = "ULUBEY" },
new City { Id = 858, provinceId = 64, Name = "UŞAK MERKEZ" },
new City { Id = 859, provinceId = 65, Name = "BAHÇESARAY" },
new City { Id = 860, provinceId = 65, Name = "BAŞKALE" },
new City { Id = 861, provinceId = 65, Name = "ÇALDIRAN" },
new City { Id = 862, provinceId = 65, Name = "ÇATAK" },
new City { Id = 863, provinceId = 65, Name = "EDREMİT" },
new City { Id = 864, provinceId = 65, Name = "ERCİŞ" },
new City { Id = 865, provinceId = 65, Name = "GEVAŞ" },
new City { Id = 866, provinceId = 65, Name = "GÜRPINAR" },
new City { Id = 867, provinceId = 65, Name = "MURADİYE" },
new City { Id = 868, provinceId = 65, Name = "ÖZALP" },
new City { Id = 869, provinceId = 65, Name = "SARAY" },
new City { Id = 870, provinceId = 65, Name = "VAN MERKEZ" },
new City { Id = 871, provinceId = 66, Name = "AKDAĞMADENİ" },
new City { Id = 872, provinceId = 66, Name = "AYDINCIK" },
new City { Id = 873, provinceId = 66, Name = "BOĞAZLIYAN" },
new City { Id = 874, provinceId = 66, Name = "ÇANDIR" },
new City { Id = 875, provinceId = 66, Name = "ÇAYIRALAN" },
new City { Id = 876, provinceId = 66, Name = "ÇEKEREK" },
new City { Id = 877, provinceId = 66, Name = "KADIŞEHRİ" },
new City { Id = 878, provinceId = 66, Name = "SARAYKENT" },
new City { Id = 879, provinceId = 66, Name = "SARIKAYA" },
new City { Id = 880, provinceId = 66, Name = "SORGUN" },
new City { Id = 881, provinceId = 66, Name = "ŞEFAATLİ" },
new City { Id = 882, provinceId = 66, Name = "YENİFAKILI" },
new City { Id = 883, provinceId = 66, Name = "YERKÖY" },
new City { Id = 884, provinceId = 66, Name = "YOZGAT MERKEZ" },
new City { Id = 885, provinceId = 67, Name = "ALAPLI" },
new City { Id = 886, provinceId = 67, Name = "ÇAYCUMA" },
new City { Id = 887, provinceId = 67, Name = "DEVREK" },
new City { Id = 888, provinceId = 67, Name = "EREĞLİ" },
new City { Id = 889, provinceId = 67, Name = "GÖKÇEBEY" },
new City { Id = 890, provinceId = 67, Name = "ZONGULDAK MERKEZ" },
new City { Id = 891, provinceId = 68, Name = "AĞAÇÖREN" },
new City { Id = 892, provinceId = 68, Name = "AKSARAY MERKEZ" },
new City { Id = 893, provinceId = 68, Name = "ESKİL" },
new City { Id = 894, provinceId = 68, Name = "GÜLAĞAÇ" },
new City { Id = 895, provinceId = 68, Name = "GÜZELYURT" },
new City { Id = 896, provinceId = 68, Name = "ORTAKÖY" },
new City { Id = 897, provinceId = 68, Name = "SARIYAHŞİ" },
new City { Id = 898, provinceId = 69, Name = "AYDINTEPE" },
new City { Id = 899, provinceId = 69, Name = "BAYBURT MERKEZ" },
new City { Id = 900, provinceId = 69, Name = "DEMİRÖZÜ" },
new City { Id = 901, provinceId = 70, Name = "AYRANCI" },
new City { Id = 902, provinceId = 70, Name = "BAŞYAYLA" },
new City { Id = 903, provinceId = 70, Name = "ERMENEK" },
new City { Id = 904, provinceId = 70, Name = "KARAMAN MERKEZ" },
new City { Id = 905, provinceId = 70, Name = "KÂZIMKARABEKİR" },
new City { Id = 906, provinceId = 70, Name = "SARIVELİLER" },
new City { Id = 907, provinceId = 71, Name = "BAHŞİLİ" },
new City { Id = 908, provinceId = 71, Name = "BALIŞEYH" },
new City { Id = 909, provinceId = 71, Name = "ÇELEBİ" },
new City { Id = 910, provinceId = 71, Name = "DELİCE" },
new City { Id = 911, provinceId = 71, Name = "KARAKEÇİLİ" },
new City { Id = 912, provinceId = 71, Name = "KESKİN" },
new City { Id = 913, provinceId = 71, Name = "KIRIKKALE MERKEZ" },
new City { Id = 914, provinceId = 71, Name = "SULAKYURT" },
new City { Id = 915, provinceId = 71, Name = "YAHŞİHAN" },
new City { Id = 916, provinceId = 72, Name = "BATMAN MERKEZ" },
new City { Id = 917, provinceId = 72, Name = "BEŞİRİ" },
new City { Id = 918, provinceId = 72, Name = "GERCÜŞ" },
new City { Id = 919, provinceId = 72, Name = "HASANKEYF" },
new City { Id = 920, provinceId = 72, Name = "KOZLUK" },
new City { Id = 921, provinceId = 72, Name = "SASON" },
new City { Id = 922, provinceId = 73, Name = "BEYTÜŞŞEBAP" },
new City { Id = 923, provinceId = 73, Name = "CİZRE" },
new City { Id = 924, provinceId = 73, Name = "GÜÇLÜKONAK" },
new City { Id = 925, provinceId = 73, Name = "İDİL" },
new City { Id = 926, provinceId = 73, Name = "SİLOPİ" },
new City { Id = 927, provinceId = 73, Name = "ŞIRNAK MERKEZ" },
new City { Id = 928, provinceId = 73, Name = "ULUDERE" },
new City { Id = 929, provinceId = 74, Name = "AMASRA" },
new City { Id = 930, provinceId = 74, Name = "BARTIN MERKEZ" },
new City { Id = 931, provinceId = 74, Name = "KURUCAŞİLE" },
new City { Id = 932, provinceId = 74, Name = "ULUS" },
new City { Id = 933, provinceId = 75, Name = "ARDAHAN MERKEZ" },
new City { Id = 934, provinceId = 75, Name = "ÇILDIR" },
new City { Id = 935, provinceId = 75, Name = "DAMAL" },
new City { Id = 936, provinceId = 75, Name = "GÖLE" },
new City { Id = 937, provinceId = 75, Name = "HANAK" },
new City { Id = 938, provinceId = 75, Name = "POSOF" },
new City { Id = 939, provinceId = 76, Name = "ARALIK" },
new City { Id = 940, provinceId = 76, Name = "IĞDIR MERKEZ" },
new City { Id = 941, provinceId = 76, Name = "KARAKOYUNLU" },
new City { Id = 942, provinceId = 76, Name = "TUZLUCA" },
new City { Id = 943, provinceId = 77, Name = "ALTINOVA" },
new City { Id = 944, provinceId = 77, Name = "ARMUTLU" },
new City { Id = 945, provinceId = 77, Name = "ÇINARCIK" },
new City { Id = 946, provinceId = 77, Name = "ÇİFTLİKKÖY" },
new City { Id = 947, provinceId = 77, Name = "TERMAL" },
new City { Id = 948, provinceId = 77, Name = "YALOVA MERKEZ" },
new City { Id = 949, provinceId = 78, Name = "EFLÂNİ" },
new City { Id = 950, provinceId = 78, Name = "ESKİPAZAR" },
new City { Id = 951, provinceId = 78, Name = "KARABÜK MERKEZ" },
new City { Id = 952, provinceId = 78, Name = "OVACIK" },
new City { Id = 953, provinceId = 78, Name = "SAFRANBOLU" },
new City { Id = 954, provinceId = 78, Name = "YENİCE" },
new City { Id = 955, provinceId = 79, Name = "ELBEYLİ" },
new City { Id = 956, provinceId = 79, Name = "KİLİS MERKEZ" },
new City { Id = 957, provinceId = 79, Name = "MUSABEYLİ" },
new City { Id = 958, provinceId = 79, Name = "POLATELİ" },
new City { Id = 959, provinceId = 80, Name = "BAHÇE" },
new City { Id = 960, provinceId = 80, Name = "DÜZİÇİ" },
new City { Id = 961, provinceId = 80, Name = "HASANBEYLİ" },
new City { Id = 962, provinceId = 80, Name = "KADİRLİ" },
new City { Id = 963, provinceId = 80, Name = "OSMANİYE MERKEZ" },
new City { Id = 964, provinceId = 80, Name = "SUMBAS" },
new City { Id = 965, provinceId = 80, Name = "TOPRAKKALE" },
new City { Id = 966, provinceId = 81, Name = "AKÇAKOCA" },
new City { Id = 967, provinceId = 81, Name = "CUMAYERİ" },
new City { Id = 968, provinceId = 81, Name = "ÇİLİMLİ" },
new City { Id = 969, provinceId = 81, Name = "DÜZCE MERKEZ" },
new City { Id = 970, provinceId = 81, Name = "GÖLYAKA" },
new City { Id = 971, provinceId = 81, Name = "GÜMÜŞOVA" },
new City { Id = 972, provinceId = 81, Name = "KAYNAŞLI" },
new City { Id = 973, provinceId = 81, Name = "YIĞILCA" }



           );

    }
}